### ISSUE TITLE
Feature: print to standard output

### ISSUE THREAD

**Issue by rpdelaney** [vixfwis/factorio-printer#4]
We read from standard input. Can we write to standard output? That might make some of my workflows easier, both in and out of the container.

**Comment by vixfwis** [comment]
You can use `-o -` to write to stdout

For example ([from recent pr](https://github.com/vixfwis/factorio-printer/pull/2#issuecomment-1551397274)):

    <~/background.png target/release/factorio-printer -b - -o ! - >out.txt

output blueprint goes to stdout, redirected to file, output image goes to /dev/null

**Comment by rpdelaney** [comment]
How about `--export-tileset`? :)

**Comment by vixfwis** [comment]
tileset with stdout/stdout should be working now after a45ecd82b2799b9b5916bd52c3a40326723b2ae8
